// src/views/sys/login/LoginForm.tsx
/*
 * @Author: bugdr
 * @Date: 2022-06-14 23:37:24
 * @LastEditors: bugdr
 * @LastEditTime: 2022-06-19 12:59:56
 * @FilePath: \react-blog-admin\src\views\sys\login\LoginForm.tsx
 * @Description:登录表单
 */
import { Button, Col, Divider, Form, Input, notification, Row } from 'antd';
import React, { FC, useState } from 'react';
import LoginFormTitle from './LoginFormTitle';
import CaptchaImage from '../../../components/CaptchaImage/CaptchaImage';
import {
  LockOutlined,
  UnlockOutlined,
  UserOutlined,
  GithubFilled,
  WechatFilled,
  AlipayCircleFilled,
  GoogleCircleFilled,
  TwitterCircleFilled,
  KeyOutlined,
} from '@ant-design/icons';
import Checkbox, { CheckboxChangeEvent } from 'antd/lib/checkbox/Checkbox';

import { LoginApi } from '/@/api/user/user';
import { ResponseCode } from '/@/utils/response';

const { Item } = Form;

const LoginForm: FC = () => {
  // 按钮加载
  const [loadingBtn, setLoadingBtn] = useState<boolean>(false);
  // 登录按钮的文字
  const [textBtn, setTextBtn] = useState<string>('登录');

  // 表单默认值
  const [initialValues, setInitialValues] = useState({
    userName: 'bugdr',
    password: '123456',
  });

  // 表单验证的规则
  const formRules = {
    userName: [{ required: true, message: '请输入独一无二的用户名' }],
    password: [{ required: true, message: '请输入密码' }],
    captcha: [{ required: true, message: '请输入图灵验证码密码' }],
  };

  // 触发登录的方法
  const onFinish = async (values: CommonObjectType<string>) => {
    setLoadingBtn(true);
    setTextBtn('正在登录中');
    // 组装数据进行登录接口的联调
    const data = { ...values };
    const result = await LoginApi(data);
    // 触发按钮加载，并且加载文字
    if (result.code === ResponseCode.SUCCESS) {
      setLoadingBtn(false);
      setTextBtn('登录成功');
      notification.success({
        message: result.message,
        description: `欢迎回来：${result.result.UserName}`,
        duration: 3,
      });
    } else {
      setLoadingBtn(false);
      setTextBtn('登录');
    }
  };
  return (
    <div>
      <LoginFormTitle />
      <Form
        className="p-4"
        size="large"
        initialValues={initialValues}
        scrollToFirstError={true}
        onFinish={onFinish}
      >
        <Item name="userName" rules={formRules.userName}>
          <Input prefix={<UserOutlined />} allowClear placeholder="请输入用户名" />
        </Item>
        <Item name="password" rules={formRules.password}>
          <Input.Password prefix={<LockOutlined />} allowClear placeholder="请输入密码" />
        </Item>
        <Item name="captcha" rules={formRules.captcha}>
          <Row gutter={12} align="middle" justify="space-between">
            <Col span={14}>
              <Input prefix={<UnlockOutlined />} allowClear placeholder="请输入图灵验证码" />
            </Col>
            <Col span={10} className="text-right">
              <CaptchaImage />
            </Col>
          </Row>
        </Item>
        <Item>
          <Row gutter={24} align="middle" justify="space-between">
            <Col span={12}>
              {/* 记住我 */}
              <Checkbox>记住我</Checkbox>
            </Col>
            <Col span={12} className="text-right">
              {/* 忘记密码 */}
              <Button type="link" size="small">
                忘记密码？
              </Button>
            </Col>
          </Row>
        </Item>
        <Item>
          <Button type="primary" block size="large" loading={loadingBtn} htmlType="submit">
            {textBtn}
          </Button>
        </Item>
        <Item>
          <div className="grid grid-cols-3 gap-2">
            <Button>手机登录</Button>
            <Button>二维码登录</Button>
            <Button>注册</Button>
          </div>
        </Item>
        {/* 分割线 */}
        <Divider>其他登录方式</Divider>
        <div className="flex justify-between text-2xl">
          <GithubFilled />
          <WechatFilled />
          <AlipayCircleFilled />
          <GoogleCircleFilled />
          <TwitterCircleFilled />
        </div>
      </Form>
    </div>
  );
};

export default LoginForm;

// src/views/sys/login/LoginForm.vue
<template>
  <LoginFormTitle v-show="getShow" class="enter-x" />
  <Form
    class="p-4 enter-x"
    :model="formData"
    :rules="getFormRules"
    ref="formRef"
    v-show="getShow"
    @keypress.enter="handleLogin"
  >
    <FormItem name="userName" class="enter-x">
      <Input
        size="large"
        v-model:value="formData.userName"
        :placeholder="t('sys.login.userName')"
        class="fix-auto-fill"
      >
        <template #prefix>
          <UserOutlined />
        </template>
      </Input>
    </FormItem>
    <FormItem name="password" class="enter-x">
      <InputPassword
        size="large"
        visibilityToggle
        v-model:value="formData.password"
        :placeholder="t('sys.login.password')"
      >
        <template #prefix>
          <LockOutlined />
        </template>
      </InputPassword>
    </FormItem>

    <FormItem name="captcha" class="enter-x">
      <Row flex justify="space-between" :gutter="12">
        <Col :span="16">
          <Input
            size="large"
            v-model:value="formData.captcha"
            :placeholder="t('sys.login.captcha')"
            class="fix-auto-fill"
          >
            <template #prefix>
              <KeyOutlined />
            </template>
          </Input>
        </Col>
        <Col :span="8">
          <CaptchaImage />
        </Col>
      </Row>
    </FormItem>

    <Row class="enter-x">
      <Col :span="12">
        <FormItem>
          <!-- No logic, you need to deal with it yourself -->
          <Checkbox v-model:checked="rememberMe" size="small">
            {{ t('sys.login.rememberMe') }}
          </Checkbox>
        </FormItem>
      </Col>
      <Col :span="12">
        <FormItem :style="{ 'text-align': 'right' }">
          <!-- No logic, you need to deal with it yourself -->
          <Button type="link" size="small" @click="setLoginState(LoginStateEnum.RESET_PASSWORD)">
            {{ t('sys.login.forgetPassword') }}
          </Button>
        </FormItem>
      </Col>
    </Row>

    <FormItem class="enter-x">
      <Button type="primary" size="large" block @click="handleLogin" :loading="loading">
        {{ t('sys.login.loginButton') }}
      </Button>
    </FormItem>
    <Row class="enter-x">
      <Col :md="8" :xs="24">
        <Button block @click="setLoginState(LoginStateEnum.MOBILE)">
          {{ t('sys.login.mobileSignInFormTitle') }}
        </Button>
      </Col>
      <Col :md="8" :xs="24" class="!my-2 !md:my-0 xs:mx-0 md:mx-2">
        <Button block @click="setLoginState(LoginStateEnum.QR_CODE)">
          {{ t('sys.login.qrSignInFormTitle') }}
        </Button>
      </Col>
      <Col :md="7" :xs="24">
        <Button block @click="setLoginState(LoginStateEnum.REGISTER)">
          {{ t('sys.login.registerButton') }}
        </Button>
      </Col>
    </Row>

    <Divider class="enter-x">{{ t('sys.login.otherSignIn') }}</Divider>

    <div class="flex justify-evenly enter-x" :class="`${prefixCls}-sign-in-way`">
      <GithubFilled />
      <WechatFilled />
      <AlipayCircleFilled />
      <GoogleCircleFilled />
      <TwitterCircleFilled />
    </div>
  </Form>
</template>
<script lang="ts" setup>
  import { reactive, ref, unref, computed } from 'vue';
  import { UserOutlined, LockOutlined } from '@ant-design/icons-vue';
  import { Checkbox, Form, Input, Row, Col, Button, Divider } from 'ant-design-vue';
  import {
    GithubFilled,
    WechatFilled,
    AlipayCircleFilled,
    GoogleCircleFilled,
    TwitterCircleFilled,
    KeyOutlined,
  } from '@ant-design/icons-vue';
  import LoginFormTitle from './LoginFormTitle.vue';
  import { useI18n } from '/@/hooks/web/useI18n';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useUserStore } from '/@/store/modules/user';
  import { LoginStateEnum, useLoginState, useFormRules, useFormValid } from './useLogin';
  import { useDesign } from '/@/hooks/web/useDesign';
  import CaptchaImage from '/@/components/CaptchaInput/src/CaptchaImage.vue';
  import { ResponseCode } from '/@/utils';

  const FormItem = Form.Item;
  const InputPassword = Input.Password;
  const { t } = useI18n();
  const { notification } = useMessage();
  const { prefixCls } = useDesign('login');
  const userStore = useUserStore();

  const { setLoginState, getLoginState } = useLoginState();
  const { getFormRules } = useFormRules();

  const formRef = ref();
  const loading = ref(false);
  const rememberMe = ref(false);

  const formData = reactive({
    userName: 'bugdr',
    password: '123456',
    captcha: '',
  });

  const { validForm } = useFormValid(formRef);

  const getShow = computed(() => unref(getLoginState) === LoginStateEnum.LOGIN);

  async function handleLogin() {
    const data = await validForm();
    if (!data) return;
    try {
      loading.value = true;
      const result = await userStore.login({
        password: data.password,
        userName: data.userName,
        captcha: data.captcha,
        mode: 'none', //不要默认的错误提示
      });
      // 做一下判空
      if (result === null) return;
      if (result.code === ResponseCode.SUCCESS) {
        notification.success({
          message: result.message,
          description: `${t('sys.login.loginSuccessDesc')}: ${result.result.userName}`,
          duration: 3,
        });
      } else {
        notification.error({
          message: result.message,
          duration: 3,
        });
      }
    } finally {
      loading.value = false;
    }
  }
</script>
