// src/views/sys/login/LoginFormTitle.vue
<!--
 * @Author: bugdr
 * @Date: 2022-05-02 14:03:13
 * @LastEditors: bugdr
 * @LastEditTime: 2022-05-04 17:11:48
 * @FilePath: \blog-admin\src\views\sys\login\LoginFormTitle.vue
 * @Description: 登录，注册等表单头部的标题
-->
<template>
  <h2 class="mb-3 text-2xl font-bold text-center xl:text-3xl enter-x xl:text-left">
    {{ getFormTitle }}
  </h2>
</template>
<script lang="ts" setup>
  import { computed, unref } from 'vue';
  import { useI18n } from '/@/hooks/web/useI18n';
  import { LoginStateEnum, useLoginState } from './useLogin';

  const { t } = useI18n();

  const { getLoginState } = useLoginState();

  const getFormTitle = computed(() => {
    const titleObj = {
      [LoginStateEnum.RESET_PASSWORD]: t('sys.login.forgetFormTitle'),
      [LoginStateEnum.LOGIN]: t('sys.login.signInFormTitle'),
      [LoginStateEnum.REGISTER]: t('sys.login.signUpFormTitle'),
      [LoginStateEnum.MOBILE]: t('sys.login.mobileSignInFormTitle'),
      [LoginStateEnum.QR_CODE]: t('sys.login.qrSignInFormTitle'),
    };
    return titleObj[unref(getLoginState)];
  });
</script>

// src/views/sys/login/LoginFormTitle.tsx
/*
 * @Author: bugdr
 * @Date: 2022-06-15 08:39:53
 * @LastEditors: bugdr
 * @LastEditTime: 2022-06-15 09:43:15
 * @FilePath: \react-blog-admin\src\views\sys\login\LoginFormTitle.tsx
 * @Description:表单的title
 */

import { FC, useMemo } from 'react';
import { LoginStateEnum, useLoginState } from './useLogin';
const LoginFormTitle: FC = () => {
  const { getLoginState } = useLoginState();
  // 计算属性计算title
  const getFormTitle = useMemo(() => {
    const titleObj = {
      [LoginStateEnum.LOGIN]: '登录',
    };
    return titleObj[getLoginState];
  }, []);
  return (
    <h2 className="mb-3 text-2xl font-bold text-center xl:text-3xl xl:text-left">{getFormTitle}</h2>
  );
};

export default LoginFormTitle;
