// src/views/article/index.tsx
/*
 * @Author: bugdr
 * @Date: 2022-07-04 08:22:40
 * @LastEditors: bugdr
 * @LastEditTime: 2022-07-05 12:55:33
 * @FilePath: \react-blog-admin\src\views\article\index.tsx
 * @Description:
 */
import { Button, Input } from 'antd';
import { FC, useState } from 'react';
import ArticleMd from './components/articleMd';
import { BsMarkdown } from 'react-icons/bs';
import { RiDraftLine } from 'react-icons/ri';
import { FiSend } from 'react-icons/fi';
import ArticleModal from './components/articleModal';

const Article: FC = () => {
  const [isModalVisible, setIsModalVisible] = useState(false);
  const showArticleModal = () => {
    setIsModalVisible(true);
  };
  return (
    <>
      <div className="bg-white">
        <div className="flex items-center p-2">
          <Input
            prefix={<BsMarkdown className="text-xl" />}
            allowClear
            className="flex-1"
            size="large"
            bordered={false}
            showCount
            maxLength={30}
            placeholder="请输入你要创作的文章标题吧..."
          />
          <div className="flex items-center justify-end">
            <Button className="mx-4" icon={<RiDraftLine />}>
              草稿箱
            </Button>
            <Button
              icon={<FiSend className="text-cyan-50" />}
              type="primary"
              onClick={() => showArticleModal()}
            >
              发布
            </Button>
          </div>
        </div>
        <div className="p-2">
          <ArticleMd />
        </div>
        <ArticleModal isModalVisible={isModalVisible} setIsModalVisible={setIsModalVisible} />
      </div>
    </>
  );
};

export default Article;

// src/views/article/index.vue
<!--
 * @Author: bugdr
 * @Date: 2022-05-09 10:58:50
 * @LastEditors: bugdr
 * @LastEditTime: 2022-05-23 13:08:03
 * @FilePath: \blog-admin\src\views\article\index.vue
 * @Description: 发布文章
-->
<template>
  <div class="p-4">
    <div class="bg-white md:flex items-center p-1">
      <div class="flex-1">
        <Input
          class="h-12"
          v-model:value="articleModel.title"
          size="large"
          placeholder="请输入文章标题(8到64字符)"
          show-count
          :maxlength="64"
          :bordered="false"
        >
          <template #prefix> <Icon icon="ph:article-medium-bold" /> </template>
        </Input>
      </div>
      <div class="flex justify-end">
        <Button class="mr-4" type="primary" ghost>
          <template #icon> <Icon icon="ri:draft-line" /> </template>
          <span>草稿箱</span></Button
        >
        <Button type="primary">
          <template #icon>
            <Icon icon="fluent:save-20-regular" />
          </template>
          <span>发布</span>
        </Button>
      </div>
    </div>
    <ArticleMdEditor />
  </div>
</template>
<script setup lang="ts">
  import { reactive, ref } from 'vue';
  import ArticleMdEditor from './components/ArticleMdEditor.vue';
  import { Input, Button } from 'ant-design-vue';
  import Icon from '/@/components/Icon';

  const articleModel = reactive({
    title: '', // 文章标题
  });
</script>
<style lang="less" scoped></style>
