// src/components/CaptchaInput/src/CaptchaImage.vue
<!--
 * @Author: bugdr
 * @Date: 2022-05-03 12:25:01
 * @LastEditors: bugdr
 * @LastEditTime: 2022-05-03 14:54:16
 * @FilePath: \blog-admin\src\components\CaptchaInput\src\CaptchaImage.vue
 * @Description: 验证码图片
-->
<template>
  <img :src="captchaValue" class="cursor-pointer" @click="changeVerifyCode" />
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { CaptchaApi } from '/@/api/sys/captcha';
  export default defineComponent({
    name: 'CaptchaImage',
    setup() {
      const captchaValue = ref('');
      async function getCaptchaImage() {
        captchaValue.value = `${CaptchaApi.GetCaptcha}`;
      }
      getCaptchaImage();
      // 切换验证码
      async function changeVerifyCode() {
        const isDate = String(new Date()); // 时间类型格式化
        captchaValue.value = `${CaptchaApi.GetCaptcha}?random=${Date.parse(isDate)}`;
      }
      return {
        captchaValue,
        changeVerifyCode,
      };
    },
  });
</script>
<style lang="less" scoped></style>

// src/components/CaptchaImage/CaptchaImage.tsx
/*
 * @Author: bugdr
 * @Date: 2022-06-15 09:58:34
 * @LastEditors: bugdr
 * @LastEditTime: 2022-06-15 10:10:35
 * @FilePath: \react-blog-admin\src\components\CaptchaImage\CaptchaImage.tsx
 * @Description:验证码图片
 */

import { FC, useEffect, useState } from 'react';
import { CaptchaApi } from '../../api/sys/captcha';

const CaptchaImage: FC = () => {
  const [captchaValue, setCaptchaValue] = useState<string | undefined>();
  //  获取图片
  const getCaptchaImage = async () => {
    const result = `${CaptchaApi.GetCaptcha}`;
    setCaptchaValue(result);
  };

  // 改变验证码
  const changeVerifyCode = async () => {
    const isDate = String(new Date()); // 时间类型格式化
    const result = `${CaptchaApi.GetCaptcha}?random=${Date.parse(isDate)}`;
    setCaptchaValue(result);
  };

  useEffect(() => {
    getCaptchaImage();
    changeVerifyCode();
  }, [getCaptchaImage, changeVerifyCode]);

  return (
    <img
      className="cursor-pointer"
      src={captchaValue}
      alt="图灵验证码"
      onClick={changeVerifyCode}
    />
  );
};

export default CaptchaImage;
