// src/views/dashboard/workbench/index.vue
<!--
 * @Author: bugdr
 * @Date: 2022-04-30 19:56:46
 * @LastEditors: bugdr
 * @LastEditTime: 2022-04-30 19:56:46
 * @FilePath: \blog-admin\src\views\dashboard\workbench\index.vue
 * @Description: 工作台
-->
<template>
    <div>workbench</div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
</script>
<style lang="scss" scoped></style>

// src/views/dashboard/workbench/index.tsx
/*
 * @Author: bugdr
 * @Date: 2022-06-20 14:41:10
 * @LastEditors: bugdr
 * @LastEditTime: 2022-06-20 20:44:27
 * @FilePath: \react-blog-admin\src\views\dashboard\workbench\index.tsx
 * @Description:工作台
 */
import { FC } from 'react';

const Workbench: FC = () => {
  return (
    <div>
      <div>这是工作台!!!</div>
    </div>
  );
};

export default Workbench;
