// src/views/settings/app/index.vue
<!--
 * @Author: bugdr
 * @Date: 2022-05-09 12:38:34
 * @LastEditors: bugdr
 * @LastEditTime: 2022-05-09 12:38:35
 * @FilePath: \blog-admin\src\views\settings\app\index.vue
 * @Description: app设置
-->
<template>
  <div>app设置，包括用户信息修改，网站信息修改，邮箱修改等</div>
</template>
<script setup lang="ts">
  import { ref } from 'vue';
</script>
<style lang="less" scoped></style>

// src/App.tsx
/*
 * @Author: bugdr
 * @Date: 2022-05-29 11:04:33
 * @LastEditors: bugdr
 * @LastEditTime: 2022-05-29 11:19:12
 * @FilePath: \react-blog-admin\src\App.tsx
 * @Description:
 */
import './App.css';
import LayoutApp from './layout';
function App() {
  return (
    <div>
      <LayoutApp />
    </div>
  );
}

export default App;
