// src/views/dashboard/analysis/index.tsx
/*
 * @Author: bugdr
 * @Date: 2022-06-20 14:40:37
 * @LastEditors: bugdr
 * @LastEditTime: 2022-06-20 14:41:51
 * @FilePath: \react-blog-admin\src\views\dashboard\analysis\index.tsx
 * @Description:分析太
 */

import { FC } from 'react';

const Analysis: FC = () => {
  return (
    <div>
      <div>这是分析页</div>
    </div>
  );
};

export default Analysis;

// src/views/dashboard/analysis/index.vue
<!--
 * @Author: bugdr
 * @Date: 2022-04-30 19:56:39
 * @LastEditors: bugdr
 * @LastEditTime: 2022-04-30 19:56:49
 * @FilePath: \blog-admin\src\views\dashboard\analysis\index.vue
 * @Description: 分析
-->
<template>
    <div>analysis</div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
</script>
<style lang="scss" scoped></style>
